import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { inngest } from '@/lib/inngest';

// Verify the webhook signature from CALL-E if you have a secret configured
// (Simplified for this example)

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    const {
      call_id,         // The unique ID generated by CALL-E
      outcome,         // E.g., 'BOOKED', 'DECLINED', 'NO_ANSWER'
      sentiment_score,
      transcript,
      recording_url,
      metadata
    } = body;

    // We passed `case_id` inside metadata when we created the call
    const caseId = metadata?.case_id;

    if (!call_id || !caseId) {
      return NextResponse.json({ error: 'Missing required call identifiers' }, { status: 400 });
    }

    // 1. Update the CallAttempt log in the database with the AI's final outcome
    const updatedCall = await prisma.callAttempt.update({
      where: { calleCallId: call_id },
      data: {
        outcome: outcome || 'ERROR',
        sentimentScore: sentiment_score,
        transcript: transcript,
        recordingUrl: recording_url,
        completedAt: new Date(),
      }
    });

    // 2. Wake up the Inngest Orchestrator!
    // This sends an event to Inngest containing the outcome.
    // Inngest's `step.waitForEvent('call.completed')` in the cascade workflow
    // will see this, un-pause the serverless function, and execute the next decision!
    await inngest.send({
      name: 'call.completed',
      data: {
        calleCallId: call_id,
        caseId: caseId,
        outcome: outcome,
        sentimentScore: sentiment_score
      }
    });

    console.log(`Webhook received: Call ${call_id} resulted in ${outcome}. Inngest notified.`);
    return NextResponse.json({ success: true, message: 'Webhook processed' }, { status: 200 });
    
  } catch (error: any) {
    console.error('Webhook processing error:', error);
    return NextResponse.json({ error: 'Failed to process webhook' }, { status: 500 });
  }
}
